# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      
      - name: Automated Github Action Maven Version Bump
        # You may pin to the exact commit or the version.
        # uses: mickem/gh-action-bump-maven-version@28b60f9e8394195362207ebb2f6041e230718e0a
        uses: mickem/gh-action-bump-maven-version@v1.0.0
        with:
          # Where to find the pom file
          pom-file: /my-app/pom.xml
          # Command to update the version
          bump-command: mvn org.codehaus.mojo:versions-maven-plugin:set -DnewVersion=@NEW_VERSION@
          # Path to version in pom file
          version-path: /project/version
          # Custom commit message for version bump commit
          commit-message: version bump

        
